version: 2
jobs:
  test-py2:
    docker:
      - image: circleci/python:2.7.17
    steps:
      - checkout
      - run: echo "Currently a no-op."
  test-py3:
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run: echo "Currently a no-op."
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-py2
      - test-py3
